import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { buildCssAndSnapshot } from "./scripts/build-css.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the GitHub repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const watch = process.argv[2] === "watch";

// CSS (and the generated src/generated/themeCss.ts module main.ts imports)
// must exist BEFORE the JS bundle is built. See ARCHITECTURE.md §9.1 for
// why this replaced an earlier runtime-disk-read design.
await buildCssAndSnapshot(prod);

const jsContext = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (watch) {
  const cssContext = await esbuild.context({
    entryPoints: ["styles/index.css"],
    bundle: true,
    outfile: "styles.css",
    logLevel: "info",
    plugins: [
      {
        name: "snapshot-theme-css-into-js",
        setup(build) {
          build.onEnd(async (result) => {
            if (result.errors.length > 0) return;
            await buildCssAndSnapshot(false);
            jsContext.rebuild();
          });
        },
      },
    ],
  });
  await cssContext.watch();
  await jsContext.watch();
} else {
  await jsContext.rebuild();
  process.exit(0);
}
