import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the GitHub repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const watch = process.argv[2] === "watch";

const jsContext = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

// Bundles every stylesheet under styles/ into a single styles.css at the
// plugin root, which is what Obsidian expects/loads automatically.
const cssContext = await esbuild.context({
  entryPoints: ["styles/index.css"],
  bundle: true,
  outfile: "styles.css",
  minify: prod,
  logLevel: "info",
});

if (watch) {
  await jsContext.watch();
  await cssContext.watch();
} else {
  await jsContext.rebuild();
  await cssContext.rebuild();
  process.exit(0);
}
