import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { readFile } from "node:fs/promises";
import { buildCss } from "./scripts/build-css.mjs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the GitHub repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const watch = process.argv[2] === "watch";
const themeCssModule = "virtual:brewvault-theme-css";
const nativePdfAssetsModule = "virtual:brewvault-native-pdf-assets";

const themeCssModulePlugin = {
  name: "brewvault-theme-css-module",
  setup(build) {
    build.onResolve({ filter: /^virtual:brewvault-theme-css$/ }, () => ({
      path: themeCssModule,
      namespace: "brewvault-theme-css",
    }));
    build.onLoad(
      { filter: /.*/, namespace: "brewvault-theme-css" },
      async () => ({
        contents: `export const BUNDLED_THEME_CSS = ${JSON.stringify(
          await readFile("styles.css", "utf8")
        )};`,
        loader: "js",
      })
    );
  },
};

const nativePdfAssetsModulePlugin = {
  name: "brewvault-native-pdf-assets-module",
  setup(build) {
    build.onResolve({ filter: /^virtual:brewvault-native-pdf-assets$/ }, () => ({
      path: nativePdfAssetsModule,
      namespace: "brewvault-native-pdf-assets",
    }));
    build.onLoad(
      { filter: /.*/, namespace: "brewvault-native-pdf-assets" },
      async () => {
        const asDataUrl = async (path) =>
          `data:image/jpeg;base64,${(await readFile(path)).toString("base64")}`;
        const asBase64 = async (path) => (await readFile(path)).toString("base64");
        return {
          contents: [
            `export const PHB_PARCHMENT_BACKGROUND = ${JSON.stringify(
              await asDataUrl("vendor/homebrewery/assets/parchmentBackground.jpg")
            )};`,
            `export const DMG_BACKGROUND = ${JSON.stringify(
              await asDataUrl("vendor/homebrewery/assets/DMG_background.jpg")
            )};`,
            `export const NATIVE_PDF_FONT_FILES = ${JSON.stringify({
              "BookInsanity.woff2": await asBase64("vendor/homebrewery/fonts/5e/Bookinsanity.woff2"),
              "BookInsanity Bold.woff2": await asBase64("vendor/homebrewery/fonts/5e/Bookinsanity Bold.woff2"),
              "BookInsanity Italic.woff2": await asBase64("vendor/homebrewery/fonts/5e/Bookinsanity Italic.woff2"),
              "BookInsanity Bold Italic.woff2": await asBase64("vendor/homebrewery/fonts/5e/Bookinsanity Bold Italic.woff2"),
              "Mr Eaves Small Caps.woff2": await asBase64("vendor/homebrewery/fonts/5e/Mr Eaves Small Caps.woff2"),
            })};`,
          ].join("\n"),
          loader: "js",
        };
      }
    );
  },
};

// CSS must exist before the virtual module snapshots it into the JS bundle.
await buildCss(prod);

const jsContext = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  plugins: [themeCssModulePlugin, nativePdfAssetsModulePlugin],
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
	...builtinModules,
	...builtinModules.map((moduleName) => `node:${moduleName}`),
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (watch) {
  const cssContext = await esbuild.context({
    entryPoints: ["styles/index.css"],
    bundle: true,
    outfile: "styles.css",
    logLevel: "info",
    plugins: [
      {
        name: "rebuild-theme-css-module",
        setup(build) {
          build.onEnd(async (result) => {
            if (result.errors.length > 0) return;
            await buildCss(false);
            await jsContext.rebuild();
          });
        },
      },
    ],
  });
  await cssContext.watch();
  await jsContext.watch();
} else {
  await jsContext.rebuild();
  process.exit(0);
}
