import esbuild from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "fs";

/**
 * Standalone CSS build step, callable on its own (as a pre-typecheck step,
 * since src/main.ts imports the file this generates) or reused from
 * esbuild.config.mjs's own CSS context for incremental rebuilds.
 */
export async function buildCssAndSnapshot(prod = false) {
	await esbuild.build({
		entryPoints: ["styles/index.css"],
		bundle: true,
		outfile: "styles.css",
		minify: prod,
		logLevel: "silent",
	});

	const cssContent = readFileSync("styles.css", "utf8");
	mkdirSync("src/generated", { recursive: true });
	writeFileSync(
		"src/generated/themeCss.ts",
		`// AUTO-GENERATED by scripts/build-css.mjs from the built styles.css.\n` +
			`// Do not edit by hand — changes will be overwritten on the next build.\n` +
			`export const BUNDLED_THEME_CSS = ${JSON.stringify(cssContent)};\n`
	);
}

// Allow `node scripts/build-css.mjs` directly.
if (import.meta.url === `file://${process.argv[1]}`) {
	await buildCssAndSnapshot(process.argv[2] === "production");
}
